version: "3"

services:
  influxdb:
    image: influxdb:1.8
    volumes:
      - influxdb-storage:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana-oss:7.2.1
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - 3001:3000

volumes:
  grafana-storage:
  influxdb-storage: